# Dependabot configuration
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  # Keep the actions in .github/workflows from going stale.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
